### ISSUE TITLE
Canary check for Opensearch

### ISSUE THREAD

**Issue by omalko394** [flanksource/canary-checker#1022]
Canary for Elasticsearch uses [go-elasticsearch](https://github.com/elastic/go-elasticsearch) to make queries.
And if the target of Canary is Opensearch instance the error occurs:
```"the client noticed that the server is not Elasticsearch and we do not support this unknown product"```.
Is there an opportunity to implement canary for Opensearch where [opensearch-go](https://github.com/opensearch-project/opensearch-go) will be used?

**Comment by moshloop** [comment]
@omalko394 - Yeh we can do that

**Comment by adityathebe** [comment]
Will create a new check
