### ISSUE TITLE
Pod check is not failing

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1028]
The Pod check currently has this message: `request timeout exceeded 0ms > 7000`

The canary should in fact fail,  as the domain is not correct. 

https://mission-control.azure.lab.flanksource.com/health?hidePassing=false&sortBy=name&sortDesc=false&labels=%257B%257D&query=pod&layout=table&checkId=0188432c-ef26-2051-594d-eb7684af3da4&timeRange=1h

**Comment by yashmehrotra** [comment]
If ingress and host are empty strings, use service name to check
