### ISSUE TITLE
Canary Graph API fixes

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1113]
- Uptime and latency should be calculated on the data range without summarization
- Based on the number of individual checks in the range, aggregate the statuses into time windows so that there are no more than 100 data points:
- 1m, 5m, 15m, 30m, 1h, 3h, 6h, 12h, 1d, 1w

Note that a time range of 1d could have 15k statuses or just 1 depending on the schedule.

e.g. time range / count = events per minute -> find the smallest time range where ( time range/events per minute <= 100)

**Comment by adityathebe** [comment]
- https://www.timescale.com/blog/how-to-write-better-queries-for-time-series-data-analysis-using-custom-sql-functions/
- https://stackoverflow.com/questions/14113469/generating-time-series-between-two-dates-in-postgresql
