### ISSUE TITLE
Switch check status sync to archive bit

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1310]
This stems from the slow queries being reported: https://grafana.demo.aws.flanksource.com/explore?orgId=1&left=%7B%22datasource%22:%22FrlGI6WIz%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22tempo%22,%22uid%22:%22FrlGI6WIz%22%7D,%22queryType%22:%22nativeSearch%22,%22serviceName%22:%22mission-control%22,%22minDuration%22:%225s%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D&right=%7B%22datasource%22:%22FrlGI6WIz%22,%22queries%22:%5B%7B%22query%22:%22691a2af97475f78c76a520cefb65a20c%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221697006116612%22,%22to%22:%221697027716612%22%7D%7D 

"SELECT check_statuses.* FROM "check_statuses" Left JOIN checks ON checks.id = check_statuses.check_id WHERE checks.agent_id = '00000000-0000-0000-0000-000000000000' AND NOW() - check_statuses.created_at <= 172800000000000 ORDER BY check_statuses.created_at"

The duration mapping as a parameter doesn't seem to work,  and this query doesn't use the index on time.  We can't change the time as the primary index (because that is what we query on) and syncing on time is not feasible as times can be created in the past. 

I think the easiest is just to add a `archive bool` column (with an index) - and then query for archive=false, and then set to archive=true after upload.

@adityathebe @yashmehrotra wdyt?

**Comment by adityathebe** [comment]
> The duration mapping as a parameter doesn't seem to work

Let me try that locally on `postgres:14` because it has been working for me on `postgres:latest`. Although if you do gorm.Debug() and copy-paste & run the query on psql the mapping doesn't work.

**Comment by adityathebe** [comment]
> I think the easiest is just to add a archive bool column (with an index) - and then query for archive=false, and then set to archive=true after upload.

Why not create another index on `created_at`?

**Comment by adityathebe** [comment]
> I think the easiest is just to add a archive bool column (with an index) - and then query for archive=false, and then set to archive=true after upload.

I think with this approach we would be limited to pushing to a single upstream. Not sure if we would need that in future, but just wanted to point that out.

**Comment by yashmehrotra** [comment]
>I think the easiest is just to add a archive bool column (with an index) - and then query for archive=false, and then set to archive=true after upload.

Okay with this, we should not use the name `archive` though, something more of `is_pushed` ?
Unless we plan to use `archive` for other functionalities as well ?

**Comment by yashmehrotra** [comment]
@adityathebe 

> Why not create another index on created_at?
Since only few rows would have the flag set as false, that index should be faster than a brin based index on created_at.

Do we have any other usecases where a created_at idx would help ?

Source: https://stackoverflow.com/a/42972924
