### ISSUE TITLE
Cron schedule does not appear to take hours into account

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1350]
e..g.  `*/3 6-21 * * 1-5` run every 3 minutes throughout the night, even though it should stop at 9pm

**Comment by adityathebe** [comment]
@moshloop Is this on canary schedules? I tested it locally and it worked fine for me. Can you point me to the particular canary?
![image](https://github.com/flanksource/canary-checker/assets/13419481/4583ec7f-ccc3-468c-8b4c-2d26e78208fe)
