### ISSUE TITLE
Occasional errors when interval defined is too low

### ISSUE THREAD

**Issue by Kaitou786** [flanksource/canary-checker#149]
When creating a canary and defining a short interval like `5`. In the controller's log, we see occasional errors like:
```
ERROR	controllers.canary	failed to patch	{"canary": "redis-canary-fail", "error": "Operation cannot be fulfilled on canaries.canaries.flanksource.com \"redis-canary-fail\": the object has been modified; please apply your changes to the latest version and try again"}
```

**Comment by yashmehrotra** [comment]
This was fixed via https://github.com/flanksource/canary-checker/pull/774

Used to occur since we were making status updates on old kubernetes objects

To confirm, I created a canary with a 5 second interval and it did not error out even once
