### ISSUE TITLE
CLI download for windows detected as a Trojan by defender

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/canary-checker#1505]
https://canarychecker.io/cli

https://github.com/flanksource/canary-checker/releases/latest/download/canary-checker.exe

<img width="512" alt="image" src="https://github.com/flanksource/canary-checker/assets/55124746/48048ecf-0150-4d4a-8181-e455252e6dab">

**Comment by moshloop** [comment]
@dabasvibhor please retest this
