### ISSUE TITLE
Kubernetes synthetic checks

### ISSUE THREAD

**Issue by RelativeSure** [flanksource/canary-checker#1747]
Hi there 👋

At my workplace, we're looking into alternatives for Kuberhealthy, as its kinda a dead project.
I want to ask if you support or will support synthetic checks such as if a pvc can be created with a specific storageclass?

Or maybe a cronjob-checker as this one https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/cronjob-checker/README.md

This project looks promising, and I hope you can get more into the market of replacing Kuberhealthy, if theres any plans of that.
Thanks in advance.

**Comment by moshloop** [comment]
@RelativeSure yes - This is currently in progress with https://github.com/flanksource/canary-checker/issues/436

**Comment by RelativeSure** [comment]
I completely forgot about this issue. So sorry!!
Is there an ETA or planned release? Can we use it in production soon?
Thanks in advance.

**Comment by moshloop** [comment]
@RelativeSure This should now be available, please check it out https://canarychecker.io/reference/kubernetes-resource - any feedback would be appreciated
