### ISSUE TITLE
When using db.external postgres connection fails, requiring SSL

### ISSUE THREAD

**Issue by krohrsb** [flanksource/canary-checker#1766]
When using db.external, the connection from canary-checker to the postgres-db fails, noting that it requires SSL to be enabled.

One can workaround this by editing the db secret's DB_URL value and adding `?sslmode=disable` to it, however it likely should be this way out of the box.

e.g.,

`postgresql://postgres:PASSWORD@postgres.canary.svc.cluster.local/canarychecker`

Becomes

`postgresql://postgres:PASSWORD@postgres.canary.svc.cluster.local/canarychecker?sslmode=disable`

Used the following DB helm values:

```
db:
    external:
      enabled: true
      create: true
```

**Comment by yashmehrotra** [comment]
@krohrsb Thanks for reporting, I have raised a PR for the fix
