### ISSUE TITLE
Latest Canary-checker-ui compatibility

### ISSUE THREAD

**Issue by kubebn** [flanksource/canary-checker#1781]
UI v1.0.618 is not working correctly with latest canary-checker [v1.0.259](https://github.com/flanksource/canary-checker/releases/tag/v1.0.259)

**Comment by mainawycliffe** [comment]
@kubebn I am currently working on this, it would be helpful if you could point some of the issues you are facing?

**Comment by mainawycliffe** [comment]
@kubebn Thanks, let me investigate

**Comment by mainawycliffe** [comment]
@kubebn, could you send me the network response for the main canary page and modal? I can't replicate this locally.

**Comment by kubebn** [comment]
@mainawycliffe 

![image](https://github.com/flanksource/canary-checker/assets/110397870/8209ac9e-fd56-4a82-a838-a40450bc2d7e)
![image](https://github.com/flanksource/canary-checker/assets/110397870/c6325a6a-68c6-4b0d-86c9-452345f42ee1)
![image](https://github.com/flanksource/canary-checker/assets/110397870/201c078b-2bc6-4195-96c4-054c63994506)
![image](https://github.com/flanksource/canary-checker/assets/110397870/4b74aafc-5c98-41ee-bdc0-79609ad7e065)

**Comment by mainawycliffe** [comment]
@kubebn Thanks. One last thing: can you share the response headers and bodies (JSON, if possible) for the following endpoints for both versions?

- /api/canary/api/summary
- /api/db/checks?check=***
- /api/canary/api/graph?check=***

**Comment by kubebn** [comment]
[check1.json](https://github.com/flanksource/canary-checker/files/15175885/check1.json)
[graphcheck1.json](https://github.com/flanksource/canary-checker/files/15175886/graphcheck1.json)
[summary1.json](https://github.com/flanksource/canary-checker/files/15175887/summary1.json)
[summary2.json](https://github.com/flanksource/canary-checker/files/15175888/summary2.json)

**Comment by kubebn** [comment]
/api/db/checks?check=***
/api/canary/api/graph?check=***

are the same for both versions.

**Comment by moshloop** [comment]
@kubebn this should be resolve with the latest prerelease  - A new version will be released next week
