### ISSUE TITLE
Text Results

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#191]
i.e. instead of just pass/fail currently supported - add a text that gets displayed in the UI and CRD status

Add support for:
- bucket check (display size, age, count)
- Junit chec (display pass/fail/html)
- SQL - return value
- HTTP return balue from json/xpath

**Comment by flanksaul** [comment]
From discussion on spec.

Row types as follows:

- Bar
   - Test type: Default
- Text
   - Test type: bucket, params: size, age, count, duration
       - Has default displayTemplate (size=humanize, age=humanize, params...)
   - Test type: Junit, params: pass, fail, duration
       - Has default displayTemplate(fail=humanize, pass=humanize, params...)
   - Test type: SQL (duration, results)
        - Action: Return value
        - No default displayTemplate
   - Test type: HTTP, params: content, duration, headers 
       - Action: Return value from json/xpath
       - No default displayTemplate
