### ISSUE TITLE
Error on startup with embedded db

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#2017]
canary-checker-757775b567-scqbl canary-checker 2024/08/01 10:16:10 logger.go:167: /app/pkg/db/canary.go:119 ERROR: insert or update on table "checks" violates foreign key constraint "checks_canary_id_fkey" (SQLSTATE 23503)

canary-checker-757775b567-scqbl canary-checker 2024/08/01 10:16:10 logger.go:167: /app/pkg/db/canary.go:429 ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification (SQLSTATE 42P10)

**Comment by adityathebe** [comment]
@moshloop cannot reproduce this.
