### ISSUE TITLE
failed to get canary while reporting

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#2232]
canary-checker-7b4747dd7f-tz7bm canary-checker {"time":"2024-10-11T11:04:42.204080881Z","level":"ERROR","msg":"failed to get canary while reporting","logger":"controllers/canary","err":"Canary.canaries.flanksource.com \"abp-microservice\" not found","canary":{"Namespace":"dev","Name":"abp-microservice"}}

**Comment by adityathebe** [comment]
@moshloop is this a mismatched namespace issue? 

cuz that canary is in `prod` namespace not `dev`


```
kg canaries -A | rg abp                                                                                                                                                                                                                                  ✘ INT|INT  17s  10:39:34
prod                  abp-microservice                        30         Failed   19s          0/720 0%           133ms        212d
prod                  abp-microservice-database                          Failed   406d         0/13 0%            10ms         406d

```
