### ISSUE TITLE
gcsBucket check 

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#265]

**Comment by Kaitou786** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CC] GCS Check](https://trello.com/c/CZ4DpiCC/73-cc-gcs-check)

**Comment by Kaitou786** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[CC] GCS Check](https://trello.com/c/CZ4DpiCC/73-cc-gcs-check)
