### ISSUE TITLE
ConnectionFailureMode

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#374]
- Failed (don't run exprs) 
- Invalid (+ fire different event, don't run exprs)
   + don't include status in lastResult function 
   + check status become invalid
- Continue (run exprs to determine status)

**Comment by yashmehrotra** [comment]
If check fails, templating should not run

**Comment by moshloop** [comment]
```yaml:

test:
     expr: error == null && status.code > 399
```

**Comment by adityathebe** [comment]
> ```
> 
> test:
>      expr: error == null && status.code > 399
> ```

If we don't run expression when the check errors out, do we need the `error == null` check in expr?
