### ISSUE TITLE
DNS Check - Add thresholdMillis

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#45]
If the request takes longer than the threshold, then the check should fail

**Comment by ikropotov** [comment]
@moshloop I was looking into this issue.
I've found that timeout for DNS checks are read from system /etc/resolv.conf file, and there is no way to set it with stdlib on runtime (except tweaking /etc/resolv.conf)
Explanation:
Here is where actual timeout for DNS call is set
https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L153

And this `exchange` func is called from `tryOneName`
https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L256
where timeOut is read from cfg *dnsConfig

And this call is initiated here
https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L595
And finally the dnsConfig is read here
https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L579

And if you carefully check that dnsConfig
https://github.com/golang/go/blob/master/src/net/dnsconfig_unix.go#L40

There is either default set for timeout
conf := &dnsConfig{
		ndots:    1,
		timeout:  5 * time.Second,
		attempts: 2,
	}

or reading it out of the hardcoded file /etc/resolv.conf
either here
https://github.com/golang/go/blob/master/src/net/dnsclient_unix.go#L337
or here
https://github.com/golang/go/blob/ca978a5ca9390dc759f20db989b49ad9cdcd81d4/src/net/conf.go#L100

So finally it gives us no option to adjust it it on runtime with any config set.

Couple of ideas is to write own dnsCheck thing, which I am not sure if worth for just having a timeout, or somehow tweak that file during calls, but I am not sure if filesystem will be quick enough for concurrent routines.
