### ISSUE TITLE
error connecting with postgres cannot parse DB_URL failed to parse as DSN (invalid dsn)

### ISSUE THREAD

**Issue by med502** [flanksource/canary-checker#630]
Canary checker pod is hanging in carashloop state.

I've performed installation both EKS based kubernetes cluster and local docker kubernetes using operator.
I cannot find in any of the manifests definition of DB_URL variable, in repository I can see it being defined in helm chart.
Is it hardcodec inside of the image?

Logs
`
W0928 08:15:17.198388       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2022-09-28T08:15:17.208Z        FATAL   error connecting with postgres: cannot parse `DB_URL`: failed to parse as DSN (invalid dsn)
`

**Comment by moshloop** [comment]
Hi med502

It is looking for a DB_URL environment variable, you can also pass this in explicitly using `--db` or use `--db embedded://` which will start an embedded version of postgres
