### ISSUE TITLE
UI - Improve check reporting graphics

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#67]
Currently, the UI just displays a Red or Green square with no visual indicator of age or duration.

Possible designs:

```
Now  ---------------      5m Ago
✓.    ✗ ✓     ✗              ✗
```
```
5h Ago ---------------    2d Ago
    ✓.    ✗ ✓     ✗               ✓   
```

Could use red/green circles and then the size of the circle to indicate the duration

**Comment by philipstaffordwood** [comment]
What about a sparkline style mini-bar chart?
A bar per check with bar height showing duration.

I'm thinking using negative values as well as colors for errors:
![image](https://user-images.githubusercontent.com/11496482/94615461-14b37a80-02a8-11eb-95d1-2d3bdc8f7dd4.png)
alternatively using just colors for errors:
![image](https://user-images.githubusercontent.com/11496482/94615659-665c0500-02a8-11eb-9515-322bdfc3e1cd.png)

Something like this kind of sizing could fit into the currently used space:

![image](https://user-images.githubusercontent.com/11496482/94618004-c81d6e80-02aa-11eb-8a37-2f7de6fb77bf.png)

**Comment by philipstaffordwood** [comment]
![image](https://user-images.githubusercontent.com/11496482/95134140-a3ba0a00-0762-11eb-8e91-3bc4817e5813.png)

**Comment by philipstaffordwood** [comment]
@moshloop Looks like we can close this one
