### ISSUE TITLE
When creating the default deployment, pods fail / crashloopbackoff due to DB

### ISSUE THREAD

**Issue by matoszz** [flanksource/canary-checker#707]
Following the vanilla instructions provided and `kubectl apply -f https://github.com/flanksource/canary-checker/releases/download/v0.38.154/release.yaml` (also tried the latest release .197, same thing) the behavior is that the pods fail due to lack of DB connection:

```
2022-12-25T18:46:50.541Z	FATAL	error connecting with postgres: cannot parse `DB_URL`: failed to parse as DSN (invalid dsn)
```

Not sure if the preference would be to:

- Not require a database at all? (preferred for me at least, but uncertain what postgres is even doing in this instanc)
- Have the default manifests use the "embedded" option (although I haven't been able to get this to work, either)
- Couple a STS / PG instance with vanilla settings so that the "one apply" deployment pattern would still work

**Comment by moshloop** [comment]
The docs now use helm as the default installer: https://canarychecker.io/getting-started/
