### ISSUE TITLE
HTTP/DNS - thresholdMillis of 0 should be considered unlimited

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#74]

**Comment by u5surf** [comment]
@moshloop Hi, I’d like to approach this issue.

I think that has two solutions, which one is adding simply 'if-else' which `check.Threshold` Mills is 0 or not, another is if Threshold Mills is not set, it sets the integer max value. 
The latter has merit that need not to change the implements of threshold timer drastically.

**Comment by moshloop** [comment]
Hi @u5surf  - I agree the latter sounds better.

**Comment by yashmehrotra** [comment]
Closing this issue as setting `thresholdMillis` to 0 behaves as no timeout/infinite wait
