### ISSUE TITLE
Add header for namespace, and remove namespace prefix in name

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#90]

**Comment by philipstaffordwood** [comment]
We discussed not having a **Namespace** Column and rather relying on grouping
![image](https://user-images.githubusercontent.com/11496482/98297167-ace60300-1fbc-11eb-8e46-c5e6876de02b.png)

But adding a "indentation" under the namespace for the grouped checks seems to look cleaner, and that layout is easier using an extra column 
![image](https://user-images.githubusercontent.com/11496482/98297491-2b42a500-1fbd-11eb-8e23-68f87de1bf1c.png)

(and if we have it we may as well label it for clarity)
![image](https://user-images.githubusercontent.com/11496482/98296697-f41fc400-1fbb-11eb-9d4d-90b9de8a0e62.png)

**Comment by moshloop** [comment]
Looks good - I think we should switch the tag from the name to namespace, and also reduce the width of the column to maybe 50 - 100px , The type column width can also be reduced

**Comment by philipstaffordwood** [comment]
OK:
Tag on namespace, not name,
Columns sized to fit contents,
Border cleanups, and
A bit of spacing between each namespace section

![image](https://user-images.githubusercontent.com/11496482/98451478-77711f00-214e-11eb-87f4-af820272fdd5.png)
